import type { Metadata } from "next";
import { Geist, Source_Code_Pro, DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const sourceMono = Source_Code_Pro({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["200", "900"],});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={dmSans.variable}>
      <body
        className={`${geistSans.variable} ${sourceMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
